language: php
sudo: false
php:
  - "5.6"
script:
  - composer install --no-dev
  - php build.php
branches:
  except:
    - release
deploy:
  provider: pages
  skip-cleanup: true
  github-token: $DEPLOYTOKEN
  target-branch: master
  local-dir: dist
  on:
    branch: devel
